# Generated by Django 4.1.2 on 2022-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("actual", models.IntegerField()),
                ("last", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=30)),
                ("estimated_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=30)),
                ("salt", models.CharField(max_length=256)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(fields=("name", "tag"), name="unique_0"),
        ),
        migrations.AddField(
            model_name="queue",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="demo_queue.service"
            ),
        ),
        migrations.AddField(
            model_name="counter",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="demo_queue.service"
            ),
        ),
        migrations.AddConstraint(
            model_name="queue",
            constraint=models.UniqueConstraint(
                fields=("date", "service"), name="unique_2"
            ),
        ),
        migrations.AddConstraint(
            model_name="counter",
            constraint=models.UniqueConstraint(
                fields=("_id", "service"), name="unique_1"
            ),
        ),
    ]
